### PR TITLE
Update t-shirt files with new logos

### PR DESCRIPTION
**Pull request by ricekot**
Related to zaproxy/zaproxy#4024.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks!

**Comment by psiinon** [comment]
The OWASP and ZAP logos on Tshirt_Do_bad_things_back.png dont look aligned to me - the ZAP one looks a bit lower? I think the centers of the circles should be in line.

Do we want the year on the tshirts? We'll have to remember to update them every year ;)

**Comment by ricekot** [comment]
Tweaked :). Changed to use "Core Team" instead of "Team \<Year\>".

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — CHANGES_REQUESTED** [review]
I dont think we should have "Core Team" swag published - thats reserved for members of the Core Team. These graphics are for anyone to download and use...

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Thanks!

**Pull request merged**
