### PR TITLE
Update posters with new ZAP logo

### PR DESCRIPTION
**Pull request by ricekot**
Update all PSDs and PNGs with new ZAP logo.
Update fonts in the "Do bad things" poster:
- Times New Roman -> Garamond
- Arial -> Franklin Gothic Book

Remove Poster_Do_bad_things_Small_white.xcf because it had no layers.

Signed-off-by: ricekot <ricekot@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
The PNG were dropped?

**Comment by ricekot** [comment]
Nope, there was a reduction in size which is why they're shown in red on GitHub... You can display the rich diff to look at the old and new images side-by-side.

**Comment by thc202** [comment]
The xcf file was actually removed.

**Comment by ricekot** [comment]
Right, the xcf file was just the "Do bad things (white)" poster imported into GIMP. It did not have any layers and wasn't useful IMO.

**Comment by ricekot** [comment]
Updated the commit message.

**Comment by kingthorin** [comment]
We should probably add a superscript circle r to all occurrences of OWASP?

`®`

(Sorry I'd forgotten about this PR.)

Ref: https://owasp.org/www-policy/operational/mark-usage-guidelines

**Comment by ricekot** [comment]
Updated with an ® symbol next to OWASP and replaced PSD (Photoshop) files with XCF (GIMP) files.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thank you!

**Pull request merged**
